@startuml
hide footbox
skinparam Style strictuml
skinparam SequenceMessageAlign center

participant "user" as User
participant ":TradeLog" as TradeLog
participant ":Parser" as Parser
participant "ac:AddCommand" as AddCommand
participant ":ParserUtil" as ParserUtil
participant "t:Trade" as Trade
participant "tl:TradeList" as TradeList
participant ":Ui" as Ui

User -> TradeLog : input "add ... strat/BB"
activate TradeLog

TradeLog -> Parser : parseCommand(...)
activate Parser
Parser -> AddCommand : new AddCommand(arguments)
activate AddCommand
Parser --> TradeLog : ac
deactivate Parser

AddCommand -> ParserUtil : parseStrategy("BB")
activate ParserUtil
ParserUtil --> AddCommand : "Breakout"
deactivate ParserUtil

AddCommand -> Trade : new Trade(..., "Breakout")
activate Trade
Trade --> AddCommand
deactivate Trade

TradeLog -> AddCommand : execute(tradeList, ui, storage)
AddCommand -> TradeList : addTrade(t)
activate TradeList
TradeList --> AddCommand
deactivate TradeList
AddCommand -> Ui : printTrade(t)
activate Ui
Ui --> AddCommand
deactivate Ui
AddCommand -> Ui : showTradeAdded()
activate Ui
Ui --> AddCommand
deactivate Ui
AddCommand --> TradeLog
deactivate AddCommand
TradeLog --> User
deactivate TradeLog
@enduml